import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/helpcenter.css";
import { ChakraProvider } from "@chakra-ui/react";

import Sidebar from "@/components/help_center/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Temacina.com | Help Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider cssVarsRoot="body">
          <div className="flex flex-col lg:flex-row overflow-x-hidden ">
            {/* Sidebar */}
            <aside className="w-full lg:w-[350px] xl:w-[400px] bg-white shadow-md border-2 border-orange-500 lg:fixed lg:h-screen lg:top-0 lg:left-0 lg:z-10 p-4">
              <Sidebar />
            </aside>

            {/* Main content */}
            <main className="flex-1  bg-white lg:ml-[350px] xl:ml-[400px] ">
              {children}
            </main>
          </div>
        </ChakraProvider>
      </body>
    </html>
  );
}
